import {
  Category,
  Hammer,
  History,
  LayoutDashboard,
  MessageSquare,
  PenTool,
  Receipt,
  Recycle,
  ScanEye,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Store,
  User,
} from "@/components/icons";
import { iconSizes, ICON_VARIANT } from "@/lib/icons";

export const adminNavIconById: Record<string, React.ReactNode> = {
  dashboard: <LayoutDashboard size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  users: <User size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  finance: <LayoutDashboard size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  orders: <ShoppingCart size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  returns: <Recycle size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  products: <Store size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "trade-in": <Recycle size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "support-requests": <PenTool size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "promo-codes": <Sparkles size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  campaigns: <Sparkles size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  bundles: <Category size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "gift-cards": <Receipt size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "customizer-quotes": <Hammer size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  home: <LayoutDashboard size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "ab-tests": <Sparkles size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  posts: <PenTool size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  moderation: <MessageSquare size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "ring-customization": <Hammer size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "back-in-stock-alerts": <History size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  settings: <SlidersHorizontal size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  media: <ScanEye size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
  "audit-logs": <Category size={iconSizes.sm} variant={ICON_VARIANT} aria-hidden />,
};
