/**
 * آیکن‌های یکپارچه پروژه — همه از iconsax-reactjs.
 * نام‌های alias برای سازگاری با استفاده‌های قبلی (ChevronLeft و …).
 */
export {
  Add as Plus,
  ArrowDown2 as ChevronDown,
  ArrowLeft,
  ArrowLeft2 as ChevronLeft,
  ArrowRight2 as ChevronRight,
  ArrowUp as ArrowUpLeft,
  BagHappy,
  Calendar,
  Category,
  ArrowSwapHorizontal as Compare,
  Check,
  Clock as History,
  CloseCircle as X,
  Crown,
  Diamonds as Gem,
  Element4 as LayoutDashboard,
  Export,
  Heart,
  I3DRotate as Rotate3d,
  Location as MapPin,
  Lock,
  Logout as LogOut,
  MagicStar as Sparkles,
  Menu,
  Message,
  MessageCircle,
  MessageSquare,
  Minus,
  PenTool,
  Personalcard as IdCard,
  ProfileCircle as UserRound,
  Receipt,
  RecoveryConvert as Recycle,
  Refresh as RefreshCw,
  Refresh,
  Refresh2,
  SearchNormal as Search,
  Setting4 as SlidersHorizontal,
  Share as Share2,
  Share,
  ShieldTick as ShieldCheck,
  Shop as Store,
  ShoppingBag,
  ShoppingCart,
  Scan as ScanEye,
  SliderHorizontal,
  Star,
  TickCircle as BadgeCheck,
  Truck,
  User,
  Verify,
  Wallet,
  PathTool as Hammer,
} from "iconsax-reactjs";

/** اسپینر بارگذاری (جایگزین Loader2) */
export { Refresh2 as Loader2 } from "iconsax-reactjs";
